[package]
authors = [
  "Tsiry Sandratraina <tsiry.sndr@fluentci.io>",
]
description = "CI/CD Plugin for Capistrano"
keywords = [
  "capistrano",
  "deploy",
]
license = "MIT"
name = "capistrano"
version = "0.1.1"
